spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect